from __future__ import annotations
from copy import deepcopy
import logging
import typing as t
from functools import partial
from enum import IntEnum
from collections import abc
from dataclasses import dataclass, field, replace
import numpy as np
import numpy.typing as npt
import pandas as pd
import yaml

from eq_solver.linalg_tools import precompute_Aprime_and_Kmap_checked
from eq_solver._types import ActivityModel
from eq_solver.activity_models import functions

logger = logging.getLogger(__name__)

class Phase(IntEnum):
    SOLID = 0
    LIQUID = 1
    GAS = 2

class Constraint(IntEnum):
    TOTAL = 0
    CHARGE = 1
    DIRECT = 2

@dataclass(frozen=True)
class Species:
    name: str
    phase: Phase = field(repr=False)

    # parameters for activity models
    a: float = field(repr=False, default=0.0)  # in nm
    b: float = field(repr=False, default=0.0)

@dataclass(frozen=True)
class Component:
    name: str
    constraint: Constraint
    base_species: Species
    base_charge: int

@dataclass(frozen=True)
class Equilibrium:
    name: str
    stoichiometry: abc.Mapping[Species, float | int]
    logK: float
    DH: float = 0.0  # in kJ/(mol*K)

    def with_temperature(self, from_T: float, to_T: float) -> Equilibrium:
        """Returns new Equilibrium object at different temperature.
        from_T, to_T must be given in Kelvin units."""
        R = 8.3145e-3  # kJ/(mol*K)
        logK_new = self.logK - self.DH / R * (1 / to_T - 1 / from_T) / np.log(10)
        return replace(self, logK=logK_new)

@dataclass
class System:
    activity_model: ActivityModel
    species: tuple[Species, ...]
    components: tuple[Component, ...]
    equilibria: tuple[Equilibrium, ...] = field(repr=False)
    temperature: float = 298.15

    # generated by __post_init__()
    stoichiometry_matrix: npt.NDArray[np.float64] = field(init=False, repr=False)
    logK: npt.NDArray[np.float64] = field(init=False, repr=False)
    specs: SystemSpecs = field(init=False)

    # required by FitFunc
    has_charge_cstr: bool = field(init=False, repr=False)
    cpt_cstr: npt.NDArray[np.uint8] = field(init=False, repr=False)
    cpt_base_idx: npt.NDArray[np.uint16] = field(init=False, repr=False)
    spc_charge: npt.NDArray[np.number] = field(init=False, repr=False)
    spc_phase: npt.NDArray[np.uint8] = field(init=False, repr=False)
    spc_logK: npt.NDArray[np.float64] = field(init=False, repr=False)
    q_ref: float = field(init=False, repr=False)  # charge when only DIRECT species exist
    gamma: abc.Callable[[float], npt.NDArray[np.float64]] = field(init=False, repr=False)
    bounds_lower: abc.Sequence[float] = field(init=False, repr=False)
    bounds_upper: abc.Sequence[float] = field(init=False, repr=False)

    def check_sanity(self):
        # check if all the species in equilibria, components are included
        for eq in self.equilibria:
            for sp in eq.stoichiometry:
                if sp not in self.species:
                    raise ValueError(f"{sp} is in equilibria, but not in system.species")
        for cpt in self.components:
            if cpt.base_species not in self.species:
                raise ValueError(f"{cpt.base_species} is in components, but not in system.species")

        # dof test
        if len(self.species) != len(self.equilibria) + len(self.components):
            raise ValueError(f"dof mismatch (len(species) != len(equilibria) + len(components))\n"
                             f"  species: {len(self.species)}\n"
                             f"  equilibria: {len(self.equilibria)}\n"
                             f"  components: {len(self.components)}")

        # check temperature
        if self.temperature < 273.15 or self.temperature > 373.15:
            logger.warning('Temperature (%s K) is below 0 or above 100 degC. Is it really desired?',
                           self.temperature)

    def __post_init__(self):
        self.check_sanity()
        self.specs = SystemSpecs.from_system(self)
        A = np.zeros((len(self.equilibria), len(self.species)))
        for i, eq in enumerate(self.equilibria):
            for sp, val in eq.stoichiometry.items():
                j = self.species.index(sp)
                A[i, j] = val
        free_idx = [self.species.index(cpt.base_species) for cpt in self.components]
        r = precompute_Aprime_and_Kmap_checked(A, free_idx)
        self.stoichiometry_matrix =  np.round(r.Aprime, 4)
        self.logK = np.round(r.T @ [eq.logK for eq in self.equilibria], 4)
        # solid and gas must be charge neutral
        cpt_charge = np.array([cpt.base_charge for cpt in self.components])
        spc_charge = self.stoichiometry_matrix @ cpt_charge
        for i, sp in enumerate(self.species):
            if sp.phase != Phase.LIQUID and spc_charge[i] != 0.0:
                raise ValueError(f"{sp} must be charge neutral.")

        self.has_charge_cstr = any(cpt.constraint == Constraint.CHARGE for cpt in self.components)
        self.cpt_cstr = np.array([cpt.constraint for cpt in self.components], dtype=np.uint8)
        self.cpt_base_idx = np.array([
            self.species.index(cpt.base_species) for cpt in self.components
        ], dtype=np.uint16)
        self.spc_charge = self.stoichiometry_matrix @ np.array([cpt.base_charge for cpt in self.components])
        self.spc_phase = np.array([sp.phase for sp in self.species], dtype=np.uint8)
        self.spc_logK = np.asarray(self.logK, dtype=float)
        self.gamma = partial(
            functions[self.activity_model],
            temp=self.temperature,
            a=np.array([sp.a for sp in self.species]),
            b=np.array([sp.b for sp in self.species]),
            z=self.spc_charge,
        )
        self.bounds_lower = ((-100.,) * self.specs.n_loga
                             + (0.,) * (self.specs.n_solid + self.specs.n_ionic_strength))
        self.bounds_upper = ((1.,) * self.specs.n_loga
                             + (10.,) * (self.specs.n_solid + self.specs.n_ionic_strength))

    def with_temperature(self, to_T: float) -> System:
        """Return a new System object at different temperature.
        to_T must be given in Kelvin unit."""
        equilibria = tuple(eq.with_temperature(self.temperature, to_T) for eq in self.equilibria)
        return replace(self, equilibria=equilibria, temperature=to_T)

    def without_component(self, name: str) -> System:
        """Remove a component from the system, and return a new System object."""
        l = [cpt for cpt in self.components if cpt.name == name]
        if not l :
            raise ValueError(f"Component {name} not in system")
        cpt = l[0]
        idx_cpt = self.components.index(cpt)
        new_species = tuple(
            spc for spc, c in zip(self.species, self.stoichiometry_matrix[:, idx_cpt]) if c == 0.0
        )
        new_components = tuple(
            cpt_ for cpt_ in self.components if cpt_ is not cpt
        )
        new_equilibria = tuple(
            eq for eq in self.equilibria if all(spc in new_species for spc in eq.stoichiometry.keys())
        )
        return replace(self,
                       species=new_species,
                       components=new_components,
                       equilibria=new_equilibria,)

    def without_species(self, *names: str) -> System:
        """Remove species from the system, and return a new System object."""
        l = [spc for spc in self.species if spc.name in names]
        if not l:
            raise ValueError(f"Species {names} not in system")
        spc_to_remove = l
        if any(spc is cpt.base_species for cpt in self.components for spc in spc_to_remove):
            raise ValueError(f'Cannot remove {spc_to_remove} because some of them are base of a component')
        new_species = tuple(spc_ for spc_ in self.species if spc_ not in spc_to_remove)
        new_equilibria = tuple(
            eq for eq in self.equilibria
            if not any(spc in eq.stoichiometry.keys() for spc in spc_to_remove)
        )
        return replace(self,
                       species=new_species,
                       equilibria=new_equilibria,)

    def stoichiometry_matrix_as_df(self) -> pd.DataFrame:
        return pd.DataFrame(self.stoichiometry_matrix,
                            columns=[cpt.base_species.name for cpt in self.components],
                            index=[sp.name for sp in self.species])

    def logK_as_df(self) -> pd.DataFrame:
        return pd.DataFrame({'logK': self.logK}, index=[sp.name for sp in self.species])

    def ionic_strength(self, spc_c: np.ndarray,
                       z_bg_pos: int = 1, z_bg_neg: int = 1) -> float:
        _m = self.spc_phase == Phase.LIQUID
        if self.has_charge_cstr:
            q_bg = 0.0
        else:
            q_bg = -spc_c[_m] @ self.spc_charge[_m]

        c_bg = np.abs(q_bg) / (z_bg_pos if q_bg > 0 else z_bg_neg)
        z_bg = z_bg_pos if q_bg > 0 else z_bg_neg

        return np.sum(0.5 * spc_c[_m] * self.spc_charge[_m] ** 2) + 0.5 * c_bg * z_bg**2

    @classmethod
    def from_yaml(cls, path) -> System:
        with open(path) as f:
            config = yaml.safe_load(f)
        return cls.from_config(config)

    @classmethod
    def from_config(cls, config) -> System:
        config = deepcopy(config)

        activity_model = config['activity_model']

        # species
        d_sp: dict[str, Species] = {}
        for sp in config['species']:
            sp['phase'] = getattr(Phase, sp['phase'].upper())
            d_sp[sp['name']] = Species(**sp)
        # components
        d_cpt: dict[str, Component] = {}
        for cpt in config['components']:
            try:
                cpt['base_species'] = d_sp[cpt['base_species']]
            except KeyError:
                raise ValueError(f'base_species {cpt["base_species"]} of component {cpt["name"]} is not in species')
            cpt['constraint'] = getattr(Constraint, cpt['constraint'].upper())
            d_cpt[cpt['name']] = Component(**cpt)
        # equilibria
        d_eq: dict[str, Equilibrium] = {}
        for eq in config['equilibria']:
            eq['stoichiometry'] = {d_sp[n]: val for n, val in eq['stoichiometry'].items()}
            d_eq[eq['name']] = Equilibrium(**eq)

        return cls(
            activity_model=activity_model,
            species=tuple(d_sp.values()),
            equilibria=tuple(d_eq.values()),
            components=tuple(d_cpt.values()),
            temperature=config['temperature'],
        )

@dataclass(frozen=True)
class SystemSpecs:
    n_vars: int
    n_loga: int
    n_solid: int
    n_ionic_strength: int
    arguments: tuple[str, ...]
    returns: tuple[str, ...]

    @classmethod
    def from_system(cls, system: System) -> SystemSpecs:
        n_loga = 0
        n_solid = 0
        n_ionic_strength = 0
        for cpt in system.components:
            if cpt.constraint != Constraint.DIRECT:
                n_loga += 1
        for sp in system.species:
            if sp.phase == Phase.SOLID:
                n_solid += 1
        if system.activity_model != 'none':
            n_ionic_strength += 1
        n_vars = n_loga + n_solid + n_ionic_strength
        arguments = _get_arguments(system)
        returns = _get_returns(system)
        return cls(
            n_vars=n_vars,
            n_loga=n_loga,
            n_solid=n_solid,
            n_ionic_strength=n_ionic_strength,
            arguments=arguments,
            returns=returns,
        )


def _get_arguments(system: System) -> tuple[str, ...]:
    """Meaning of each element of x"""
    # log(activity) of free components
    args = [f'Log a({cpt.base_species.name})' for cpt in system.components if cpt.constraint != Constraint.DIRECT]
    # amount of solid phases
    for sp in system.species:
        if sp.phase == Phase.SOLID:
            args.append(f'Amount of solid {sp.name}')
    # ionic strength if activity != 'none'
    if system.activity_model != 'none':
        args.append(f'Ionic strength')
    return tuple(args)

def _get_returns(system: System) -> tuple[str, ...]:
    """Meaning of each element of return values"""
    returns = [f'Conservation of component "{cpt.name}"' for cpt in system.components
               if cpt.constraint == Constraint.TOTAL]
    for sp in system.species:
        if sp.phase == Phase.SOLID:
            returns.append(f'Solid-liquid equilibrium for {sp.name}')
    if any(cpt.constraint == Constraint.CHARGE for cpt in system.components):
        returns.append(f'Charge neutrality')
    if system.activity_model != 'none':
        returns.append(f'Self-consistency of Ionic strength')
    return tuple(returns)
